---
resource_types:
- name: google-cloud-storage
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: platform-automation-tasks
  type: google-cloud-storage
  source:
    bucket: ((gcs_bucket_name))
    regexp: platform-automation-tasks-(1.*).zip
    json_key: |
      ((gcp_credentials))

- name: harbor-product
  type: google-cloud-storage
  source:
    bucket: ((gcs_bucket_name))
    regexp: harbor-container-registry-(.*).pivotal
    json_key: |
      ((gcp_credentials))

- name: variable
  type: google-cloud-storage
  source:
    bucket: ((gcs_bucket_name))
    versioned_file: harbor-vars.yml
    json_key: |
      ((gcp_credentials))

- name: platform-automation-image
  type: google-cloud-storage
  source:
    bucket: ((gcs_bucket_name))
    regexp: platform-automation-image-(1.*).tgz
    json_key: |
      ((gcp_credentials))

- name: env
  type: google-cloud-storage
  source:
    bucket: ((gcs_bucket_name))
    versioned_file: env.yml
    json_key: |
      ((gcp_credentials))

- name: pks-essentials-code
  type: git
  source:
    uri: https://github.com/platform-acceleration-lab/pks-essentials-code.git
    branch: master

jobs:
- name: upload-and-configure-harbor
  plan:
  - aggregate:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: env
    - get: harbor-product
    - get: pks-essentials-code
    - get: variable
  - task: upload-and-stage-harbor
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-and-stage-product.yml
    input_mapping:
      env: env
      product: harbor-product
    params:
      ENV_FILE: env.yml
  - task: configure-harbor
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      env: env
      config: pks-essentials-code
      vars: variable
    params:
      ENV_FILE: env.yml
      CONFIG_FILE: config/harbor-gcp-config.yml
      VARS_FILES: vars/harbor-vars.yml
  - task: apply-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: env.yml
