---
iaas-configuration:
  project: ((PROJECT_ID))
  default_deployment_tag: ((SUBDOMAIN_NAME))
  auth_json: ((GCP_CREDENTIALS))
director-configuration:
  ntp_servers_string: metadata.google.internal
  post_deploy_enabled: true
  resurrector_enabled: true
  retry_bosh_deploys: true
az-configuration:
- name: us-central1-a
- name: us-central1-b
- name: us-central1-c
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((SUBDOMAIN_NAME))-pcf-network/((SUBDOMAIN_NAME))-infrastructure-subnet/us-central1
      cidr: 10.0.0.0/26
      dns: 169.254.169.254
      gateway: 10.0.0.1
      reserved_ip_ranges: 10.0.0.1-10.0.0.9
      availability_zone_names:
      - us-central1-a
      - us-central1-b
      - us-central1-c
  - name: pks
    subnets:
    - iaas_identifier: ((SUBDOMAIN_NAME))-pcf-network/((SUBDOMAIN_NAME))-pks-subnet/us-central1
      cidr: 10.0.10.0/24
      dns: 169.254.169.254
      gateway: 10.0.10.1
      reserved_ip_ranges: 10.0.10.1-10.0.10.9
      availability_zone_names:
      - us-central1-a
      - us-central1-b
      - us-central1-c
  - name: pks-services
    subnets:
    - iaas_identifier: ((SUBDOMAIN_NAME))-pcf-network/((SUBDOMAIN_NAME))-pks-services-subnet/us-central1
      cidr: 10.0.11.0/24
      dns: 169.254.169.254
      gateway: 10.0.11.1
      reserved_ip_ranges: 10.0.11.1-10.0.11.9
      availability_zone_names:
      - us-central1-a
      - us-central1-b
      - us-central1-c
network-assignment:
  network:
    name: infrastructure
  singleton_availability_zone:
    name: us-central1-a
resource-configuration:
  compilation:
    instances: 8
