---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: opsman-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: 2\.4\.(.*) # pin to version 2.4.x
    sort_by: semver

jobs:
- name: fetch-opsman
  plan:
  - get: opsman-pivnet
    trigger: true
    params:
      globs:
      - "*onGCP.yml"
  - aggregate:
    - put: opsman-product
      params:
        file: opsman-pivnet/OpsManager*onGCP.yml
