---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: daily-trigger
  type: time
  source:
    interval: 24h

- name: config
  type: git
  source:
    uri: ((config-uri))
    branch: master
    private_key: |
      ((config-private-key))

- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: platform-automation
    product_version: 3\.0
    sort_by: semver

- name: platform-automation-tasks
  type: gcs
  source:
    regexp: platform-automation-tasks-(.*).zip
    bucket: ((gcs-bucket))
    json_key: |
      ((gcp-credentials))

- name: platform-automation-image
  type: gcs
  source:
    regexp: platform-automation-image-(.*).tgz
    bucket: ((gcs-bucket))
    json_key: |
      ((gcp-credentials))

- name: opsman-product
  type: gcs
  source:
    regexp: ops-manager-gcp-*.yml
    bucket: ((gcs-bucket))
    json_key: |
      ((gcp-credentials))

- name: pks-product
  type: gcs
  source:
    regexp: pivotal-container-service-(.*).pivotal
    bucket: ((gcs-bucket))
    json_key: |
      ((gcp-credentials))

- name: pks-stemcell
  type: gcs
  source:
    regexp: pks-stemcell/light-bosh-stemcell-(.*)-google.*\.tgz
    bucket: ((gcs-bucket))
    json_key: |
      ((gcp-credentials))

jobs:
- name: fetch-platform-automation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - in_parallel:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz

- name: fetch-opsman
  plan:
  - in_parallel:
    - get: daily-trigger
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: config
  - &credhub-interpolate-config
    task: credhub-interpolate-config
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CA_CERT: ((credhub-ca-cert))
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      PREFIX: /concourse/main
      INTERPOLATION_PATH: ((config-dir))
    input_mapping:
      files: config
    output_mapping:
      interpolated-files: config
  - task: download-opsman-image
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: ((config-dir))/ops-manager/config-pivnet.yml
  - in_parallel:
    - put: opsman-product
      params:
        file: downloaded-product/*

- name: fetch-pks
  plan:
  - in_parallel:
    - get: daily-trigger
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: config
  - *credhub-interpolate-config
  - task: download-pks-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: ((config-dir))/pivotal-container-service/config-pivnet.yml
    output_mapping: {downloaded-stemcell: pks-stemcell}
  - in_parallel:
    - put: pks-product
      params:
        file: downloaded-product/*.pivotal
    - put: pks-stemcell
      params:
        file: pks-stemcell/*.tgz
